apiVersion: apps/v1
kind: Deployment
metadata:
  name: cooasis-upload-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cooasis-upload-service
  template:
    metadata:
      labels:
        app: cooasis-upload-service
    spec:
      containers:
      - name: upload-service
        image: <DOCKERHUB_USERNAME>/cooasis-upload-service:latest
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: cooasis-upload-service
spec:
  selector:
    app: cooasis-upload-service
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
