name: CI-CD Pipeline

on:
  push:
    branches: [making-monolith]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: |
          cd backend/auth-service && npm install
          cd ../dashboard-service && npm install
          cd ../upload-service && npm install

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            cd /coasis-backend-v0.1./backend
            git pull origin making-monolith
            pm2 restart all
